[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.26"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false


[fuzz]
runs = 10

[invariant]
runs = 10_000
depth = 50
fail_on_revert = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 
base= "${BASE_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
